version: '3'

services:

  # Socialnet API - NestJS
  socialnet_api:
    build: .
    image: socialnet_api
    env_file:
      - ./.env.dev
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mailpit
      - postgres

  # Redis for QUEUES
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"

  postgres:
    image: postgres:bullseye
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # Mailpit for send (port: 1025) emails and visualize it (port: 8025)
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"